"""empty message

Revision ID: 846e3a210fdb
Revises: 5cd1d81ac976
Create Date: 2025-07-05 13:39:21.350305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '846e3a210fdb'
down_revision: Union[str, None] = '5cd1d81ac976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'user'"), nullable=False))
        batch_op.add_column(sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'active'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
